APP_VERSION_MAJOR = 0
APP_VERSION_MINOR = 1
APP_VERSION_PATCH = 0
APP_RELEASE_TYPE = "pre-alpha"
APP_VERSION_PREFIX = "v"
if APP_RELEASE_TYPE != "":
    APP_RELEASE_TYPE = f"-{APP_RELEASE_TYPE}"
APP_VERSION_STRING = f"{APP_VERSION_PREFIX}{APP_VERSION_MAJOR}.{APP_VERSION_MINOR}.{APP_VERSION_PATCH}{APP_RELEASE_TYPE}"
